// Partner images for home slider and partners page
// This file is AUTO-GENERATED by scripts/generate-partner-images.js
// Run: npm run generate:partners (or node scripts/generate-partner-images.js)
// DO NOT edit this file manually - add/remove images in the folders instead

export const PARTNER_IMAGES = {
  // Home page partners slider (white text versions)
  homeSlider: [
    'assets/images/Partners White Text Without Background/573521118_18541182556065137_6745484161360848157_n-Photoroom.png',
    'assets/images/Partners White Text Without Background/ADSB.png-Photoroom.png',
    'assets/images/Partners White Text Without Background/MOET_Horizontal_RGB_A.png',
    'assets/images/Partners White Text Without Background/Mair_upscaled.png',
    'assets/images/Partners White Text Without Background/Makani_upscaled.png',
    'assets/images/Partners White Text Without Background/Ministry-of-Human-Resources-&-Emiratisation-_upscaled.png',
    'assets/images/Partners White Text Without Background/Ministry-of-foreign-affairs.png',
    'assets/images/Partners White Text Without Background/SAAS properties_upscaled.png',
    'assets/images/Partners White Text Without Background/Shahat.png',
    'assets/images/Partners White Text Without Background/baniyas-sc-seeklogo.png',
    'assets/images/Partners White Text Without Background/bawabat-alsharq-mall-logo.png',
    'assets/images/Partners White Text Without Background/craiyon_upscaled.png',
    'assets/images/Partners White Text Without Background/dubai-sports-council-thumb.png',
    'assets/images/Partners White Text Without Background/emirates center for strategic studies and research_upscaled.png',
    'assets/images/Partners White Text Without Background/mubadala.png',
    'assets/images/Partners White Text Without Background/umex_and_simtex_upscaled.png'
  ],

  // Partners page (colored PNG versions)
  partnersPage: [
    'assets/images/Amyal PNG Partners/573521118_18541182556065137_6745484161360848157_n-Photoroom.png',
    'assets/images/Amyal PNG Partners/ADSB.png-Photoroom.png',
    'assets/images/Amyal PNG Partners/MOET_Horizontal_RGB_A.png',
    'assets/images/Amyal PNG Partners/Makani.png',
    'assets/images/Amyal PNG Partners/Ministry-of-Human-Resources-&-Emiratisation-.png',
    'assets/images/Amyal PNG Partners/Ministry-of-foreign-affairs.png',
    'assets/images/Amyal PNG Partners/SAAS properties.png',
    'assets/images/Amyal PNG Partners/Shahat.png',
    'assets/images/Amyal PNG Partners/baniyas-sc-seeklogo.png',
    'assets/images/Amyal PNG Partners/bawabat-alsharq-mall-logo.png',
    'assets/images/Amyal PNG Partners/craiyon.png',
    'assets/images/Amyal PNG Partners/dubai-sports-council-thumb.png',
    'assets/images/Amyal PNG Partners/emirates center for strategic studies and research.png',
    'assets/images/Amyal PNG Partners/mair green.png',
    'assets/images/Amyal PNG Partners/mubadala.png',
    'assets/images/Amyal PNG Partners/umex_and_simtex.png'
  ]
};
